[project]
name = "zenohmwe"
version = "0.1.0"
description = "Add a short description here"
authors = ["Silvio Traversaro <silvio@traversaro.it>"]
channels = ["conda-forge"]
platforms = ["linux-64", "win-64"]

[tasks]
configure = { cmd = [
    "cmake",
    "-DCMAKE_BUILD_TYPE=Release",
    "-DBUILD_TESTING:BOOL=ON",
    # Use the cross-platform Ninja generator
    "-G",
    "Ninja",
    # The source is in the root directory
    "-S",
    ".",
    # We wanna build in the .build directory
    "-B",
    ".build",
]}

build = { cmd = "cmake --build .build --config Release", depends_on = ["configure"] }
pub = { cmd = "./.build/pub", depends_on = ["build"] }
sub = { cmd = "./.build/sub", depends_on = ["build"] }

[dependencies]
compilers = ">=1.7.0,<1.8"
cmake = ">=3.30.1,<3.31"
pkg-config = ">=0.29.2,<0.30"
make = ">=4.3,<5"
ninja = ">=1.12.1,<1.13"
rust = ">=1.79.0,<1.80"
