[project]
name = "zenohmwe"
version = "0.1.0"
description = "Add a short description here"
authors = ["Silvio Traversaro <silvio@traversaro.it>"]
channels = ["conda-forge"]
platforms = ["linux-64", "win-64"]

[tasks]
configure = { cmd = [
    "cmake",
    "-DCMAKE_BUILD_TYPE=Release",
    "-DBUILD_TESTING:BOOL=ON",
    # Use the cross-platform Ninja generator
    "-G",
    "Ninja",
    # The source is in the root directory
    "-S",
    ".",
    # We wanna build in the .build directory
    "-B",
    ".build",
]}

build = { cmd = "cmake --build .build --config Release", depends_on = ["configure"] }
post_build = { cmd = "echo ", depends_on = ["build"]}
pub = { cmd = "./.build/pub", depends_on = ["post_build"] }
sub = { cmd = "./.build/sub", depends_on = ["post_build"] }

[target.win-64.tasks]
# Workaround for zenoh-c putting the .dll in the wrong place
post_build = { cmd = "cp ./.build/_deps/zenohc-build/release/target/release/zenohc.dll ./.build/", depends_on = ["build"], inputs = [".build/_deps/zenohc-build/release/target/release/zenohc.dll"], outputs = [".build/zenohc.dll"]}


[dependencies]
compilers = ">=1.7.0,<1.8"
cmake = ">=3.30.1,<3.31"
pkg-config = ">=0.29.2,<0.30"
make = ">=4.3,<5"
ninja = ">=1.12.1,<1.13"
rust = ">=1.79.0,<1.80"
spdlog = ">=1.13.0,<1.14"
libboost-devel = ">=1.85.0,<1.86"
